import type { FormattedFinancesData, MetricKey, StackedAreaSeries } from '@/modules/networks/types'

export const getStackedAreaSeries = (
  financesData: FormattedFinancesData,
  selectedMetric: MetricKey,
  isLightMode: boolean,
) => {
  const series: StackedAreaSeries[] = [
    {
      type: 'line',
      name: 'Legacy Other',
      stack: 'a',
      stackStrategy: 'all',
      areaStyle: {},
      emphasis: { focus: 'series' },
      showSymbol: false,
      data: financesData[selectedMetric].legacyOthers,
      itemStyle: {
        color: '#9da6b9',
      },
    },
    {
      type: 'line',
      name: 'Legacy Core Units',
      stack: 'a',
      stackStrategy: 'all',
      areaStyle: {},
      emphasis: { focus: 'series' },
      showSymbol: false,
      data: financesData[selectedMetric].legacyCoreUnits,
      itemStyle: {
        color: '#ced3dc',
      },
    },
    {
      type: 'line',
      name: 'Governance Scope',
      stack: 'b',
      stackStrategy: 'all',
      areaStyle: {},
      emphasis: { focus: 'series' },
      showSymbol: false,
      data: financesData[selectedMetric].governanceScope,
      itemStyle: { color: '#ff82a1' },
    },
    {
      type: 'line',
      name: 'Stability Scope',
      stack: 'b',
      stackStrategy: 'all',
      areaStyle: {},
      emphasis: { focus: 'series' },
      showSymbol: false,
      data: financesData[selectedMetric].stability,
      itemStyle: { color: '#329DFF' },
    },
    {
      type: 'line',
      name: 'Support Scope',
      stack: 'b',
      stackStrategy: 'all',
      areaStyle: {},
      emphasis: { focus: 'series' },
      showSymbol: false,
      data: financesData[selectedMetric].support,
      itemStyle: { color: isLightMode ? 'rgb(248, 133, 126)' : 'rgb(248, 133, 126)' },
    },
    {
      type: 'line',
      name: 'Protocol Scope',
      stack: 'b',
      stackStrategy: 'all',
      areaStyle: {},
      emphasis: { focus: 'series' },
      showSymbol: false,
      data: financesData[selectedMetric].protocol,
      itemStyle: { color: '#4FC86F' },
    },
    {
      type: 'line',
      name: 'Accessibility Scope',
      stack: 'b',
      stackStrategy: 'all',
      areaStyle: {},
      emphasis: { focus: 'series' },
      showSymbol: false,
      data: financesData[selectedMetric].accessibility,
      itemStyle: { color: '#8E55EA' },
    },
    {
      type: 'line',
      name: 'Atlas Immutable Budget',
      stack: 'b',
      stackStrategy: 'all',
      areaStyle: {},
      emphasis: { focus: 'series' },
      showSymbol: false,
      data: financesData[selectedMetric].immutable,
      itemStyle: { color: '#FFA132' },
    },
  ]
  return series
}

export const getLegendSeries = (years: string[]) => [
  `Q1-${years[0]}`,
  'Q2',
  'Q3',
  'Q4',
  `Q1-${years[1]}`,
  'Q2',
  'Q3',
  'Q4',
  `Q1-${years[2]}`,
  'Q2',
  'Q3',
  'Q4',
  `Q1-${years[3]}`,
  'Q2',
  'Q3',
  'Q4',
]
