export enum TabSection {
  ACCOUNT_SNAPSHOT = 'account-snapshot',
  EXPENSE_REPORTS = 'expense-reports',
}

// TODO: remove the following types once we integrate the API

export enum BudgetStatus {
  Draft = 'Draft',
  Review = 'Review',
  Escalated = 'Escalated',
  Final = 'Final',
  AutoGenerated = 'AutoGenerated',
}

export enum ResourceType {
  AlignedDelegates = 'AlignedDelegates',
  CoreUnit = 'CoreUnit',
  Delegates = 'Delegates',
  Keepers = 'Keepers',
  EcosystemActor = 'EcosystemActor',
  Scopes = 'Scopes',
  SpecialPurposeFund = 'SpecialPurposeFund',
  System = 'System',
}

export interface ChangeTrackingParams {
  coreUnit?: {
    id: number
    code: string
    shortCode: string
  }
  owner?: {
    id: number
    code: string
    shortCode: string
    type: ResourceType
  }
  budgetStatementId?: number
  month?: string

  author?: {
    id: number
    username: string
  }
  commentId?: number
  status?: {
    old: BudgetStatus
    new: BudgetStatus
  }
}

export interface ChangeTrackingEvent {
  id: string
  created_at: string
  update_at?: string
  event: string
  params: ChangeTrackingParams
  description: string
}

export enum AuditStatusEnum {
  Escalated = 'Escalated',
  NeedActionsBeforeApproval = 'NeedActionsBeforeApproval',
  ApprovedWithComments = 'ApprovedWithComments',
  Approved = 'Approved',
}

export interface AuditReport {
  id: string
  budgetStatementId: string
  auditStatus: AuditStatusEnum
  reportUrl: string
  timestamp: string
}

export interface BudgetStatementFTEs {
  id?: string
  budgetStatementId?: string
  month: string
  ftes: number
}

export interface BudgetStatementMKRVest {
  id: string
  budgetStatementId?: string
  vestingDate: string
  mkrAmount: number
  mkrAmountOld: number
  comments: string
}

export interface BudgetStatementLineItem {
  id?: string
  budgetStatementWalletId?: string
  month?: string
  position?: number
  group?: string
  budgetCategory?: string
  forecast?: number
  actual: number
  comments?: string
  canonicalBudgetCategory?: string
  headcountExpense?: boolean
  budgetCap?: number
  payment?: number
  budgetId?: string
  currency?: string
}

export interface BudgetStatementPayment {
  id: string
  budgetStatementWalletId: string
  transactionDate: string
  transactionId: string
  budgetStatementLineItemId: string
  comments: string
}

export interface Source {
  code: string
  url: string
  title: string
}

export interface Target {
  amount: number
  calculation: string
  description: string
  source: Source
}

export interface BudgetStatementTransferRequest {
  id: string
  budgetStatementWalletId: string
  budgetStatementPaymentId: string
  requestAmount: number
  walletBalance: number
  walletBalanceTimeStamp: string
  target: Target
}

export interface BudgetStatementWallet {
  id: string
  budgetStatementId: string
  name: string
  address: string
  currentBalance: number
  topupTransfer: number
  comments: string
  budgetStatementLineItem: BudgetStatementLineItem[]
  budgetStatementPayment: BudgetStatementPayment[]
  budgetStatementTransferRequest: BudgetStatementTransferRequest[]
}

export enum RoleEnum {
  SuperAdmin = 'SuperAdmin',
  CoreUnitFacilitator = 'CoreUnitFacilitator',
  CoreUnitAuditor = 'CoreUnitAuditor',
  DelegatesAdmin = 'DelegatesAdmin',
  DelegatesAuditor = 'DelegatesAuditor',
  User = 'User',
}

export interface UserRole {
  id: string
  name: RoleEnum
  permissions: string[]
}

export interface BaseUser {
  id: string
  username: string
}

export interface User extends BaseUser {
  active: boolean
  roles: UserRole[]
}

export interface BudgetStatementComment {
  id: string
  budgetStatementId: string
  timestamp: string
  comment: string
  status: BudgetStatus
  author: User | BaseUser
}

export interface BudgetStatement {
  id: string
  owner: {
    id: string
    icon: string
    name: string
    shortCode: string
  }
  ownerType: string
  month: string
  status?: BudgetStatus
  ownerCode: string
  mkrProgramLength: number
  publicationUrl: string | null
  activityFeed: ChangeTrackingEvent[]
  auditReport: AuditReport[]
  budgetStatementFTEs: BudgetStatementFTEs[]
  budgetStatementMKRVest: BudgetStatementMKRVest[]
  budgetStatementWallet: BudgetStatementWallet[]
  comments: BudgetStatementComment[]
  actualExpenses: number | null
  forecastExpenses: number | null
  paymentsOnChain: number | null
  netProtocolOutflow: number | null
}
