import type { FormattedFinancesData, MetricKey } from './components/stacket-area-chart'
import type { StackedAreaSeries } from './type'

export const getStackedAreaSeries = (
  financesData: FormattedFinancesData,
  selectedMetric: MetricKey,
) => {
  const series: StackedAreaSeries[] = [
    {
      type: 'line',
      name: 'Legacy Other',
      stack: 'a',
      stackStrategy: 'all',
      areaStyle: {},
      emphasis: { focus: 'series' },
      showSymbol: false,
      data: financesData[selectedMetric].legacyOthers,
      itemStyle: { color: '#C2C9D7' },
    },
    {
      type: 'line',
      name: 'Legacy Core Units',
      stack: 'a',
      stackStrategy: 'all',
      areaStyle: {},
      emphasis: { focus: 'series' },
      showSymbol: false,
      data: financesData[selectedMetric].legacyCoreUnits,
      itemStyle: { color: '#D4D9E1' },
    },
    {
      type: 'line',
      name: 'Governance Scope',
      stack: 'b',
      stackStrategy: 'all',
      areaStyle: {},
      emphasis: { focus: 'series' },
      showSymbol: false,
      data: financesData[selectedMetric].governanceScope,
      itemStyle: { color: '#635CFF' },
    },
    {
      type: 'line',
      name: 'Stability Scope',
      stack: 'b',
      stackStrategy: 'all',
      areaStyle: {},
      emphasis: { focus: 'series' },
      showSymbol: false,
      data: financesData[selectedMetric].stability,
      itemStyle: { color: '#2563EB' },
    },
    {
      type: 'line',
      name: 'Support Scope',
      stack: 'b',
      stackStrategy: 'all',
      areaStyle: {},
      emphasis: { focus: 'series' },
      showSymbol: false,
      data: financesData[selectedMetric].support,
      itemStyle: { color: '#DC2626' },
    },
    {
      type: 'line',
      name: 'Protocol Scope',
      stack: 'b',
      stackStrategy: 'all',
      areaStyle: {},
      emphasis: { focus: 'series' },
      showSymbol: false,
      data: financesData[selectedMetric].protocol,
      itemStyle: { color: '#10B981' },
    },
    {
      type: 'line',
      name: 'Accessibility Scope',
      stack: 'b',
      stackStrategy: 'all',
      areaStyle: {},
      emphasis: { focus: 'series' },
      showSymbol: false,
      data: financesData[selectedMetric].accessibility,
      itemStyle: { color: '#8B5CF6' },
    },
    {
      type: 'line',
      name: 'Atlas Immutable Budget',
      stack: 'b',
      stackStrategy: 'all',
      areaStyle: {},
      emphasis: { focus: 'series' },
      showSymbol: false,
      data: financesData[selectedMetric].immutable,
      itemStyle: { color: '#F59E0B' },
    },
  ]
  return series
}
