import type { FormattedFinancesData, MetricKey } from './components/stacked-area-chart'
import type { StackedAreaSeries } from './type'

export const getStackedAreaSeries = (
  financesData: FormattedFinancesData,
  selectedMetric: MetricKey,
) => {
  const series: StackedAreaSeries[] = [
    {
      type: 'line',
      name: 'Legacy Other',
      stack: 'a',
      stackStrategy: 'all',
      areaStyle: {},
      emphasis: { focus: 'series' },
      showSymbol: false,
      data: financesData[selectedMetric].legacyOthers,
      itemStyle: {
        color: 'var(--color-chart-7)',
      },
    },
    {
      type: 'line',
      name: 'Legacy Core Units',
      stack: 'a',
      stackStrategy: 'all',
      areaStyle: {},
      emphasis: { focus: 'series' },
      showSymbol: false,
      data: financesData[selectedMetric].legacyCoreUnits,
      itemStyle: {
        color: 'var(--color-chart-8)',
      },
    },
    {
      type: 'line',
      name: 'Governance Scope',
      stack: 'b',
      stackStrategy: 'all',
      areaStyle: {},
      emphasis: { focus: 'series' },
      showSymbol: false,
      data: financesData[selectedMetric].governanceScope,
      itemStyle: { color: 'var(--color-fusion)' },
    },
    {
      type: 'line',
      name: 'Stability Scope',
      stack: 'b',
      stackStrategy: 'all',
      areaStyle: {},
      emphasis: { focus: 'series' },
      showSymbol: false,
      data: financesData[selectedMetric].stability,
      itemStyle: { color: 'var(--color-status-progress)' },
    },
    {
      type: 'line',
      name: 'Support Scope',
      stack: 'b',
      stackStrategy: 'all',
      areaStyle: {},
      emphasis: { focus: 'series' },
      showSymbol: false,
      data: financesData[selectedMetric].support,
      itemStyle: { color: 'var(--color-chart-6)' },
    },
    {
      type: 'line',
      name: 'Protocol Scope',
      stack: 'b',
      stackStrategy: 'all',
      areaStyle: {},
      emphasis: { focus: 'series' },
      showSymbol: false,
      data: financesData[selectedMetric].protocol,
      itemStyle: { color: 'var(--color-status-success)' },
    },
    {
      type: 'line',
      name: 'Accessibility Scope',
      stack: 'b',
      stackStrategy: 'all',
      areaStyle: {},
      emphasis: { focus: 'series' },
      showSymbol: false,
      data: financesData[selectedMetric].accessibility,
      itemStyle: { color: 'var(--color-purple)' },
    },
    {
      type: 'line',
      name: 'Atlas Immutable Budget',
      stack: 'b',
      stackStrategy: 'all',
      areaStyle: {},
      emphasis: { focus: 'series' },
      showSymbol: false,
      data: financesData[selectedMetric].immutable,
      itemStyle: { color: 'var(--color-to-do)' },
    },
  ]
  return series
}

export const getLegendSeries = (years: string[]) => [
  `Q1-${years[0]}`,
  'Q2',
  'Q3',
  'Q4',
  `Q1-${years[1]}`,
  'Q2',
  'Q3',
  'Q4',
  `Q1-${years[2]}`,
  'Q2',
  'Q3',
  'Q4',
  `Q1-${years[3]}`,
  'Q2',
  'Q3',
  'Q4',
]
