export enum ResourceType {
  AlignedDelegates = 'AlignedDelegates',
  CoreUnit = 'CoreUnit',
  Delegates = 'Delegates',
  Keepers = 'Keepers',
  EcosystemActor = 'EcosystemActor',
  Scopes = 'Scopes',
  SpecialPurposeFund = 'SpecialPurposeFund',
  System = 'System',
}

export enum BudgetStatus {
  Draft = 'Draft',
  Review = 'Review',
  Escalated = 'Escalated',
  Final = 'Final',
  AutoGenerated = 'AutoGenerated',
}

export enum TeamStatus {
  Progress = 'Progress',
  'To Do' = 'To Do',
  Canceled = 'Canceled',
  Accepted = 'Accepted',
  Obsolete = 'Obsolete',
}

export enum TeamCategory {
  Technical = 'Technical',
  Support = 'Support',
  Operational = 'Operational',
  Business = 'Business',
  RWAs = 'RWAs',
  Growth = 'Growth',
  Finance = 'Finance',
  Legal = 'Legal',
  AdvisoryCouncilMember = 'AdvisoryCouncilMember',
  ActiveEcosystemActor = 'ActiveEcosystemActor',
  ScopeFacilitator = 'ScopeFacilitator',
}

export enum ActorCategory {
  AdvisoryCouncilMember = 'AdvisoryCouncilMember',
  ActiveEcosystemActor = 'ActiveEcosystemActor',
  ScopeFacilitator = 'ScopeFacilitator',
}

export enum ProgressStatus {
  DRAFT = 'DRAFT',
  TODO = 'TODO',
  IN_PROGRESS = 'IN_PROGRESS',
  FINISHED = 'FINISHED',
}
